# Generated by Django 3.0 on 2019-12-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_checker', '0003_auto_20191212_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='general_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
