# Generated by Django 3.0 on 2019-12-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_checker', '0004_auto_20191212_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='general_link',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='general_link',
            field=models.CharField(max_length=200),
        ),
    ]
