# Generated by Django 3.0 on 2019-12-12 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_checker', '0005_auto_20191212_2251'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
