# Generated by Django 3.0 on 2019-12-12 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_checker', '0007_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='general_link',
        ),
    ]
