# Generated by Django 3.0 on 2019-12-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_checker', '0008_remove_post_general_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='general_link',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Link',
        ),
    ]
