# Generated by Django 3.0 on 2019-12-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_checker', '0009_auto_20191213_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='general_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
