# Generated by Django 3.0 on 2019-12-13 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_checker', '0011_auto_20191213_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='user',
        ),
    ]
