# Generated by Django 3.0 on 2019-12-13 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_checker', '0012_remove_link_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
    ]
