# Generated by Django 3.0 on 2019-12-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_checker', '0013_delete_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_time',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
