# Generated by Django 3.0 on 2019-12-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_checker', '0014_post_post_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='page_img_link',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
