# Generated by Django 3.0 on 2019-12-19 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_checker', '0016_post_page_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='page_id',
        ),
        migrations.CreateModel(
            name='PageId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(max_length=100)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_checker.Post')),
            ],
        ),
    ]
