# Generated by Django 3.0 on 2019-12-19 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_checker', '0017_auto_20191219_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageid',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='page_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='post_checker.PageId'),
            preserve_default=False,
        ),
    ]
