# Generated by Django 3.0 on 2019-12-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_checker', '0018_auto_20191219_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='page_id',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='PageId',
        ),
    ]
