# Generated by Django 3.0.1 on 2019-12-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_checker', '0021_auto_20191220_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_author',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
